### ISSUE TITLE
Lightnote not showing USB logo

### ISSUE THREAD

**Issue by avegancafe** [cardonabits/lightnote-update#1]
Hi, I'm trying to follow this guide and I plugged in my lightnote into my computer, and held down the button for a few seconds, but not seeing the USB logo, all I see is a QR code that goes to https://lightnote.cardonabits.com/. Is there any troubleshooting options available? Mine seems to have only one 6 step puzzle

**Comment by jcard0na** [comment]
Hi Kyle,

Let me address the second problem first:
 >Mine seems to have only one 6 step puzzle

What happens after you complete the 6th step?  Does it go back to the first?  Are you sure that it is not showing the next puzzle (maybe a similar puzzle, also with 6 moves)?  Units ship with more than 25,000 puzzles pre-loaded.  I really cannot think how it would ship with only one puzzle...

Regarding the USB logo, can you check with a different cable?  Sometimes faulty USB cables can charge, but fail to transfer data.  The USB logo only shows up after a long button press IF there is a successful USB enumeration.
The QR code, on the other hand, shows up on a short-long press, regardless of USB state.

Best,

**Comment by avegancafe** [comment]
@jcard0na Ahh I see, after I cycle through the sixth step it goes back to the first step yeah. I'll try another cable when I get home as well, I had tried two but both might have just been charging cables and not data cables or something. I'm wondering if I had bought from a fake site making clones or something, I had noticed the button was black instead of yellow too.

**Comment by avegancafe** [comment]
Ah I think I got it to work by using a different USB-c cable and re-flashing the rom! are all the puzzles 6 steps? I'm going through them and I think there are a bunch of them but hard to tell 'cause I am a noob at chess and can't quite remember all of the positions ahah

**Comment by jcard0na** [comment]
Oh, glad to hear that you resolved both problems.

There are many 6-move problems (i.e. mate in 3).  But as you progress, you will find longer problems.  Problems have different degrees of difficulty, so I'm sure that you'll find some adequate to your level.

And now that you have a cable that works, if you get fed up with chess, you can installing [hiragana alphabet](https://github.com/cardonabits/lightnote-update/blob/main/roms/lightnote-hiragana.rom)!

Best,
Javier

**Comment by avegancafe** [comment]
I actually just showed this to one of my friends and they got excited 'cause they like both chess and learning Japanese! Very cool. But sounds great, thanks for the info and sanity check haha.

Cheers,
Kyle
